from tkinter import *
window = Tk()
window.title("Remind")
window.geometry("300x250")
window.wm_iconbitmap(r"C:\Users\jaeyoung\Desktop\snowman.ico")
window.configure(background = "pink")
logo = PhotoImage(file = r"C:\Users\jaeyoung\Desktop\snack.gif")
imagelabel = Label(image = logo)
imagelabel.place(x = 30, y = 20, width = 150, height =200)
window.mainloop()
